// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, fs, port;

  express = require('express');

  app = express();

  fs = require('fs');

  app.use(express.logger());

  app.get('/', function(request, response) {
    var buffer;

    buffer = fs.readFileSync("index.html");
    response.header("Content-Type", "text/html");
    return response.send(buffer.toString());
  });

  port = process.env.PORT || 8080;

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
